import { PredefinedAsset } from "@/app/Types";
import {
  AcquisitionSource,
  AssetType,
  InvestmentType,
  TransactionType,
} from "@/lib/generated/prisma/enums";
import {
  Bitcoin,
  CircleDollarSign,
  Coins,
  PiggyBank,
  Star,
  TrendingUp,
  Wallet,
} from "lucide-react";

export const DEFAULT_CATEGORIES = [
  // EXPENSE
  { name: "Food", type: TransactionType.EXPENSE },
  { name: "Transport", type: TransactionType.EXPENSE },
  { name: "Entertainment", type: TransactionType.EXPENSE },
  { name: "Shopping", type: TransactionType.EXPENSE },
  { name: "Health", type: TransactionType.EXPENSE },
  { name: "Other", type: TransactionType.EXPENSE },
  // INCOME
  { name: "Salary", type: TransactionType.INCOME },
  { name: "Freelance", type: TransactionType.INCOME },
  { name: "Business", type: TransactionType.INCOME },
  { name: "Other", type: TransactionType.INCOME },
];

export const DEFAULT_ASSETS = [
  { name: "Cash", type: AssetType.CASH },
  { name: "Bank", type: AssetType.BANK },
  { name: "Property", type: AssetType.PROPERTY },
  { name: "Vehicle", type: AssetType.VEHICLE },
  { name: "Other", type: AssetType.OTHER },
  { name: "Gold", type: AssetType.GOLD },
] as const;

export const ACQUISITION_SOURCES = [
  { name: "Gifted", value: AcquisitionSource.GIFTED },
  { name: "Inherited", value: AcquisitionSource.INHERITED },
  { name: "Other", value: AcquisitionSource.OTHER },
  { name: "Purchased", value: AcquisitionSource.PURCHASED },
];

export const DEFAULT_INVESTMENT_TYPES = [
  { name: "Stock", value: InvestmentType.STOCK },
  { name: "Crypto", value: InvestmentType.CRYPTO },
  { name: "Gold", value: InvestmentType.GOLD },
  { name: "Other", value: InvestmentType.OTHER },
];

export const DEFAULT_ACTIONS = [
  {
    icon: Star,
    label: "Goals",
    value: "goals",
  },
  {
    icon: Wallet,
    label: "Add Assets",
    value: "assets",
  },
  {
    icon: PiggyBank,
    label: "Add Investments",
    value: "savings",
  },
  {
    icon: Wallet,
    label: "Add Transaction",
    value: "expense",
  },
];

export const PREDEFINED_ASSETS: PredefinedAsset[] = [
  // ── Gold ────────────────────────────────────────────────────────────────────
  {
    identifier: "gold",
    ticker: "gold", // handled by metals.live, not Yahoo Finance
    label: "Gold",
    type: "GOLD",
    unit: "gram",
  },

  // ── IDX Blue Chips ───────────────────────────────────────────────────────────
  {
    identifier: "BBCA.JK",
    ticker: "BBCA.JK",
    label: "Bank Central Asia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BBRI.JK",
    ticker: "BBRI.JK",
    label: "Bank Rakyat Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BMRI.JK",
    ticker: "BMRI.JK",
    label: "Bank Mandiri",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "TLKM.JK",
    ticker: "TLKM.JK",
    label: "Telkom Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ASII.JK",
    ticker: "ASII.JK",
    label: "Astra International",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "GOTO.JK",
    ticker: "GOTO.JK",
    label: "GoTo Gojek Tokopedia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BYAN.JK",
    ticker: "BYAN.JK",
    label: "Bayan Resources",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "UNVR.JK",
    ticker: "UNVR.JK",
    label: "Unilever Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ICBP.JK",
    ticker: "ICBP.JK",
    label: "Indofood CBP",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "KLBF.JK",
    ticker: "KLBF.JK",
    label: "Kalbe Farma",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "INDF.JK",
    ticker: "INDF.JK",
    label: "Indofood Sukses Makmur",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "SMGR.JK",
    ticker: "SMGR.JK",
    label: "Semen Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ANTM.JK",
    ticker: "ANTM.JK",
    label: "Aneka Tambang (Antam)",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PTBA.JK",
    ticker: "PTBA.JK",
    label: "Bukit Asam",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ADRO.JK",
    ticker: "ADRO.JK",
    label: "Adaro Energy",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "EXCL.JK",
    ticker: "EXCL.JK",
    label: "XL Axiata",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PGAS.JK",
    ticker: "PGAS.JK",
    label: "Perusahaan Gas Negara",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "JSMR.JK",
    ticker: "JSMR.JK",
    label: "Jasa Marga",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "WSKT.JK",
    ticker: "WSKT.JK",
    label: "Waskita Karya",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PWON.JK",
    ticker: "PWON.JK",
    label: "Pakuwon Jati",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },

  // ── US Stocks ────────────────────────────────────────────────────────────────
  // Note: US stock prices from Yahoo Finance are in USD — converted to IDR in fetch-prices
  {
    identifier: "AAPL",
    ticker: "AAPL",
    label: "Apple",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "MSFT",
    ticker: "MSFT",
    label: "Microsoft",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "GOOGL",
    ticker: "GOOGL",
    label: "Alphabet (Google)",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "NVDA",
    ticker: "NVDA",
    label: "NVIDIA",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "AMZN",
    ticker: "AMZN",
    label: "Amazon",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "META",
    ticker: "META",
    label: "Meta Platforms",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "TSLA",
    ticker: "TSLA",
    label: "Tesla",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "BRK-B",
    ticker: "BRK-B",
    label: "Berkshire Hathaway B",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },
  {
    identifier: "JPM",
    ticker: "JPM",
    label: "JPMorgan Chase",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },
  {
    identifier: "V",
    ticker: "V",
    label: "Visa",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },

  // ── Crypto ───────────────────────────────────────────────────────────────────
  // CoinGecko IDs (not symbols) are used as identifiers
  {
    identifier: "bitcoin",
    ticker: "bitcoin",
    label: "Bitcoin",
    type: "CRYPTO",
    unit: "coin",
  },
  {
    identifier: "ethereum",
    ticker: "ethereum",
    label: "Ethereum",
    type: "CRYPTO",
    unit: "coin",
  },
];

export const PREDEFINED_STOCKS_ASSETS: PredefinedAsset[] = [
  // ── IDX Blue Chips ───────────────────────────────────────────────────────────
  {
    identifier: "BBCA.JK",
    ticker: "BBCA.JK",
    label: "Bank Central Asia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BBRI.JK",
    ticker: "BBRI.JK",
    label: "Bank Rakyat Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BMRI.JK",
    ticker: "BMRI.JK",
    label: "Bank Mandiri",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "TLKM.JK",
    ticker: "TLKM.JK",
    label: "Telkom Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ASII.JK",
    ticker: "ASII.JK",
    label: "Astra International",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "GOTO.JK",
    ticker: "GOTO.JK",
    label: "GoTo Gojek Tokopedia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "BYAN.JK",
    ticker: "BYAN.JK",
    label: "Bayan Resources",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "UNVR.JK",
    ticker: "UNVR.JK",
    label: "Unilever Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ICBP.JK",
    ticker: "ICBP.JK",
    label: "Indofood CBP",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "KLBF.JK",
    ticker: "KLBF.JK",
    label: "Kalbe Farma",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "INDF.JK",
    ticker: "INDF.JK",
    label: "Indofood Sukses Makmur",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "SMGR.JK",
    ticker: "SMGR.JK",
    label: "Semen Indonesia",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ANTM.JK",
    ticker: "ANTM.JK",
    label: "Aneka Tambang (Antam)",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PTBA.JK",
    ticker: "PTBA.JK",
    label: "Bukit Asam",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "ADRO.JK",
    ticker: "ADRO.JK",
    label: "Adaro Energy",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "EXCL.JK",
    ticker: "EXCL.JK",
    label: "XL Axiata",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PGAS.JK",
    ticker: "PGAS.JK",
    label: "Perusahaan Gas Negara",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "JSMR.JK",
    ticker: "JSMR.JK",
    label: "Jasa Marga",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "WSKT.JK",
    ticker: "WSKT.JK",
    label: "Waskita Karya",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },
  {
    identifier: "PWON.JK",
    ticker: "PWON.JK",
    label: "Pakuwon Jati",
    type: "STOCK",
    exchange: "IDX",
    unit: "lot",
  },

  // ── US Stocks ────────────────────────────────────────────────────────────────
  // Note: US stock prices from Yahoo Finance are in USD — converted to IDR in fetch-prices
  {
    identifier: "AAPL",
    ticker: "AAPL",
    label: "Apple",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "MSFT",
    ticker: "MSFT",
    label: "Microsoft",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "GOOGL",
    ticker: "GOOGL",
    label: "Alphabet (Google)",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "NVDA",
    ticker: "NVDA",
    label: "NVIDIA",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "AMZN",
    ticker: "AMZN",
    label: "Amazon",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "META",
    ticker: "META",
    label: "Meta Platforms",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "TSLA",
    ticker: "TSLA",
    label: "Tesla",
    type: "STOCK",
    exchange: "NASDAQ",
    unit: "share",
  },
  {
    identifier: "BRK-B",
    ticker: "BRK-B",
    label: "Berkshire Hathaway B",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },
  {
    identifier: "JPM",
    ticker: "JPM",
    label: "JPMorgan Chase",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },
  {
    identifier: "V",
    ticker: "V",
    label: "Visa",
    type: "STOCK",
    exchange: "NYSE",
    unit: "share",
  },
];

export const PREDEFINED_CRYPTO_ASSETS: PredefinedAsset[] = [
  {
    identifier: "bitcoin",
    ticker: "bitcoin",
    label: "Bitcoin",
    type: "CRYPTO",
    unit: "coin",
  },
  {
    identifier: "ethereum",
    ticker: "ethereum",
    label: "Ethereum",
    type: "CRYPTO",
    unit: "coin",
  },
];

export const TYPE_ICON = {
  STOCK: {
    icon: TrendingUp,
    className: "text-blue-500 bg-blue-100",
  },
  CRYPTO: {
    icon: Bitcoin,
    className: "text-orange-500 bg-orange-100",
  },
  GOLD: {
    icon: Coins,
    className: "text-yellow-500 bg-amber-200",
  },
  OTHER: {
    icon: CircleDollarSign,
    className: "text-gray-500 bg-gray-100",
  },
} as const;
