// app/api/export/route.ts
import { auth } from "@/auth";
import { TransactionType } from "@/lib/generated/prisma/enums";
import { canExportData } from "@/lib/helper/plan";
import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const exportQuerySchema = z.object({
  from: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "must be YYYY-MM-DD")
    .optional(),
  to: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "must be YYYY-MM-DD")
    .optional(),
});

/** Columns are exactly what /api/import accepts, so a file round-trips. */
const COLUMNS = ["date", "amount", "type", "category", "description"] as const;

function csvCell(value: string) {
  // Quote only when necessary; double up any embedded quotes.
  return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

/**
 * Transaction dates are stored as UTC instants but always *mean* a calendar day
 * in Indonesia, so format them there — plain `toISOString()` slices a day off
 * anything recorded in the evening WIB.
 */
const jakartaDate = new Intl.DateTimeFormat("en-CA", {
  timeZone: "Asia/Jakarta",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});

export async function GET(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    if (!canExportData(session.user.plan)) {
      return NextResponse.json(
        { message: "Export is available on the Elite plan." },
        { status: 403 },
      );
    }

    const parsed = exportQuerySchema.safeParse(
      Object.fromEntries(req.nextUrl.searchParams),
    );
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }

    const { from, to } = parsed.data;

    const transactions = await prisma.transaction.findMany({
      where: {
        userId: session.user.id,
        // SAVINGS and INVESTMENTS rows are generated by Clarus alongside a goal
        // or holding. Exporting them would let a re-import double-count money
        // the app already tracks, and /api/import rejects those types anyway.
        type: { in: [TransactionType.INCOME, TransactionType.EXPENSE] },
        ...(from || to
          ? {
              date: {
                ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}),
                ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}),
              },
            }
          : {}),
      },
      select: {
        date: true,
        amount: true,
        type: true,
        description: true,
        category: { select: { name: true } },
      },
      orderBy: { date: "asc" },
    });

    const rows = transactions.map((t) =>
      [
        jakartaDate.format(t.date),
        t.amount.toNumber().toString(),
        t.type,
        t.category?.name ?? "",
        t.description ?? "",
      ]
        .map(csvCell)
        .join(","),
    );

    const csv = [COLUMNS.join(","), ...rows].join("\r\n");
    const filename = `clarus-transactions-${jakartaDate.format(new Date())}.csv`;

    return new NextResponse(csv, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch {
    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 },
    );
  }
}
